---
name: Run tests

on:
  - push

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    container:
      image: oalders/developer-perl
    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Install author deps
        run: dzil authordeps | xargs cpm install -g
      - name: Maybe debug Install author deps
        if: failure()
        run: cat ~/.perl-cpm/build.log
      - name: Build
        run: dzil build --no-tgz --in dzil_build_dir
      - uses: actions/upload-artifact@master
        with:
          name: build_dir
          path: dzil_build_dir
  test:
    runs-on: ubuntu-latest
    name: Test distribution
    needs: build
    strategy:
      matrix:
        perl-version:
          - "5.10"
          # - "5.12" not sure why the tests fail on this Perl
          - "5.14"
          - "5.16"
          - "5.18"
          - "5.20"
          - "5.22"
          - "5.24"
          - "5.26"
          - "5.28"
          - "5.30"
    container:
      image: oalders/tester-perl:${{ matrix.perl-version }}
      env:
        AUTHOR_TESTING: 1
        PERL_COVERAGE_VERSION: 5.30
        RELEASE_TESTING: 1
    steps:
      - uses: actions/download-artifact@master
        with:
          name: build_dir
          path: .
      - name: Install deps
        if: success()
        run: cpm install -g --cpanfile cpanfile --with-develop --with-suggests
      - name: Maybe debug Install deps
        if: failure()
        run: cat ~/.perl-cpm/build.log
      - name: Run Tests with coverage
        if: success() && matrix.perl-version == env.PERL_COVERAGE_VERSION
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
          HARNESS_PERL_SWITCHES: "-MDevel::Cover=+ignore,^local/|^t/|^xt"
        run: prove -lvr --jobs 2 t xt && cover -report codecov
      - name: Run Tests
        if: success() && matrix.perl-version != env.PERL_COVERAGE_VERSION
        run: prove -lvr --jobs 2 t xt
